spring:

  main:
    allow-bean-definition-overriding: true

#  elasticsearch:
#    uris: ${SPRING_ELASTICSEARCH_URIS}
#    data:
#      elasticsearch:
#        repositories:
#          enabled: true
#        client:
#          reactive:
#            endpoints: localhost:9200
#    username: elastic
#    password: passwordpw

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  application:
    name: iShop

  devtools:
    restart:
      enabled: true
      exclude: static/**,public/**

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 2
#      idle-timeout: 30000
#      max-lifetime: 1800000
#      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto:
#        create-drop
        update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    senderName: ${EMAIL_SENDER}
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true


# bakong khqr configuration
payment:
  token: ${PAYMENT_ACCESS_TOKEN}
  account-name: ${PAYMENT_ACCOUNT_NAME}
  account-number: ${PAYMENT_ACCOUNT_NUMBER}
  bakong-account-id: ${PAYMENT_BAKONG_ACCOUNT_ID}
  bakong-api-url: ${PAYMENT_BAKONG_API_URL}
  acquiring-bank: ${PAYMENT_ACQUIRING_BANK}
  md5-verification-url: ${MD5_VERIFICATION_URL}


# swagger ui url
springdoc:
  swagger-ui:
    path: /techco-api-ui.html
    url: /techco-api-docs
    display-request-duration: true
    doc-expansion: none
    operations-sorter: alpha
  api-docs:
    path: /techco-api-docs
  packages-to-scan: co.istad.techco.techco  # Scan your base package


client-path: login/verify-email

# token generation
keys:
  access-private-token: keys/access-private
  access-public-token: keys/access-public
  refresh-public-token: keys/refresh-public
  refresh-private-token: keys/refresh-private

media:
  server-path: "src/main/resources/filestorage/techco-medias"
  client-path: "/media/**"
  base-uri: ${MEDIA_BASE_URI}

server:
  port: 8081
  address: 0.0.0.0